### ISSUE TITLE
All i* ones work and all a* ones don't

### ISSUE THREAD

**Issue by zenVentzi** [leveluptuts/React-Apollo-Snippets-for-VSCode#3]
First of all, thank you for sharing! I find it strange though, why would only the i* ones work? I tried different scopes, yet to no avail. Also restarting vscode multiple times. Any ideas? Thanks!

**Comment by bunasQ** [comment]
hi, having the same problem ? 
@zenVentzi 
did you fix it?

**Comment by zenVentzi** [comment]
@Serjobas unfortunately not

**Comment by itsjzt** [comment]
@zenVentzi @Serjobas I made a PR that fixes that issue 👍
